name: The Trip Blog
favicon: null
layout_spectrum: 0.21410533669404685
typography_spectrum: 0.41938946349546313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5165505055338144
  lightness: 0.5952628578525037
  saturation: 0.8654658938758075
  rhythmicContrast: 0.4684273365419358
purpose: []
